name: "web-block"
services:
  cors-proxy:
    image: cors-proxy
    environment:
      - ALLOW_ORIGIN=https://lempac.github.io/web-block/
    ports:
      - "127.0.0.1:9998:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - "127.0.0.1:8003:8000"
    volumes:
      - dbdata:/var/www/database:rw
      - storage:/var/www/storage:rw

volumes:
  dbdata:
  storage:
