name: "web-block"

services:
  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:3000"  # Adjust the port as needed
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust the port as needed
    volumes:
      - .:/var/www
      - dbdata:/var/www/database
    networks:
      - app-network

volumes:
  dbdata:  # Define the volume for the SQLite database

networks:
  app-network:
    driver: bridge
