/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle an incoming authentication request. */
        post: operations["bc76a9d52929cab7a147ca7b5c527430"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Destroy an authenticated session. */
        delete: operations["250045954f07adf40103e33a04e5d715"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["0487fbb4c6d40e317fb4ec45582d09e5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["34a24a8f777c83598c6c30936c6f9a04"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle an incoming registration request. */
        post: operations["apiRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{project}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display a listing of the resource. */
        get: operations["10eca818648caf716977d244ad606c5f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a newly created resource in storage. */
        post: operations["1dd0ffd5fff7170b9eb63bc88abafb8e"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{block}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified resource. */
        get: operations["620ba86a781f786819b86f7659a2ace8"];
        /** Update the specified resource in storage. */
        put: operations["6d6ed5337b57e93ccfc607d3ae3ead93"];
        post?: never;
        /** Remove the specified resource from storage. */
        delete: operations["78f914110185aacb3dee70019e5a6e6b"];
        options?: never;
        head?: never;
        patch: operations["cc10f4e526e45e01f129e6568eb2aff6"];
        trace?: never;
    };
    "/api/blocks/{block}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified resource childern. */
        get: operations["c857e2bdf63b37450c516ae264893aae"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display a listing of the resource. */
        get: operations["8d4a13ef3fc773ff4031e515460919ea"];
        put?: never;
        /** Store a newly created resource in storage. */
        post: operations["a4dd4c17bf5fc24c224357f03dcc848a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a newly created resource in storage. */
        post: operations["5dae9d6654a488de0a9e7fc0a8800669"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified resource. */
        get: operations["1352e06e55f6ab10d3702509cd385918"];
        /** Update the specified resource in storage. */
        put: operations["a93b65e3037bfd5ea5cdc1b3dd11ba53"];
        post?: never;
        /** Remove the specified resource from storage. */
        delete: operations["63c289a907902132dd95dd7ecb50143f"];
        options?: never;
        head?: never;
        patch: operations["ee35632abc0168537257bd8f5baa9f30"];
        trace?: never;
    };
    "/api/translations/{locale}/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["b890df2c0f1546a31de76aeaf6375924"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["971db9bc974c0e607288cfe7ecc10096"];
        put: operations["fd4f39f7820d3f3cbc259c5b30fed830"];
        post?: never;
        delete: operations["db0c8ea1c902ed078a87cf1fa6497994"];
        options?: never;
        head?: never;
        patch: operations["ea88adacb890b864b59bcce5aff2473d"];
        trace?: never;
    };
    "/api/user/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["f8741720bfaafb5c8126e8c1418a9917"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["54ba995c0c13dd114980733de45f7ffa"];
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["57ddbc5bebe0cd30c268a0d8a4640660"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["75f8f589d8162c3ebb0a27049232e804"];
        trace?: never;
    };
    "/api/user/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["395814df2599dc7a564535035ede73fb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/repo/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["5dcb8b09ef61f0dd409ac3fbf1c59d74"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorObject: {
            /** @example Validation failed. */
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        Lang: "lv" | "en";
        /** @enum {string} */
        PanelPosition: "top-left" | "top-right" | "top-center" | "bottom-left" | "bottom-center" | "bottom-right";
        /** @enum {string} */
        Themes: "light" | "dark" | "cupcake" | "bumblebee" | "emerald" | "corporate" | "synthwave" | "retro" | "cyberpunk" | "valentine" | "halloween" | "garden" | "forest" | "aqua" | "lofi" | "pastel" | "fantasy" | "wireframe" | "black" | "luxury" | "dracula" | "cmyk" | "autumn" | "business" | "acid" | "lemonade" | "night" | "coffee" | "winter" | "dim" | "nord" | "sunset";
        /**
         * @deprecated
         * @enum {string}
         */
        VisibilityType: "private" | "public";
        AuthTokenResponse: {
            /** @example Login successful */
            message: string;
            /**
             * @description Sanctum plain text API token
             * @example 1|abcdefghijklmnopqrstuvwxyzabcdefg
             */
            token: string;
        };
        RegisterRequest: {
            name: string;
        } & components["schemas"]["LoginRequest"];
        LangObject: {
            [key: string]: string | components["schemas"]["LangObject"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /** @default true */
            remember: boolean;
        };
        DeleteUserRequest: {
            /** Format: password */
            password: string;
        };
        IndexProjectRequest: {
            name: string;
        };
        StoreBlockRequest: {
            x: number;
            y: number;
            width: number;
            height: number;
            path: string;
            content: string | null;
        };
        StoreClientProjectRequest: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            x: number;
            y: number;
            /** Format: float */
            zoom: number;
            default_branch: string;
            url?: string;
            oid: string;
            cwd: string;
        };
        StoreProjectRequest: {
            nameOrUrl: string;
        };
        UpdateBlockRequest: {
            x: number;
            y: number;
            width: number;
            height: number;
            path: string;
            content: string | null;
        };
        /** @description Request to update user password */
        UpdatePasswordRequest: {
            /** Format: password */
            oldPassword?: string;
            /** Format: password */
            newPassword?: string;
            /** Format: password */
            newPassword_confirmation: string;
        };
        UpdateProjectRequest: {
            name: string;
            description: string | null;
            x: number;
            y: number;
            /** Format: float */
            zoom: number;
        };
        /** @description Request for updating user style */
        UpdateStyleRequest: components["schemas"]["Style"];
        /** @description Request to update user information */
        UpdateUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string | null;
            settings: {
                /**
                 * Format: enum
                 * @enum {string}
                 */
                lang: "en" | "lv";
                hideExtensions: boolean;
                /** @default main */
                defaultBranch: string;
            };
        };
        Block: {
            id: number;
            /** @default 0 */
            x: number;
            /** @default 0 */
            y: number;
            /** @default 0 */
            width: number;
            /** @default 0 */
            height: number;
            path: string;
            is_file: boolean;
            is_folder: boolean;
            block_id?: number | null;
            project_id?: number;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @default 0 */
            x: number;
            /** @default 0 */
            y: number;
            /**
             * Format: float
             * @default 1
             */
            zoom: number;
            /** @default main */
            default_branch: string;
            url: string;
            oid: string;
            /** @default / */
            cwd: string;
        };
        /** @description User keybinds */
        Keybinds: {
            /** @default Control+p */
            quickCommand: string;
        };
        /** @description User style */
        Style: {
            controlPosition: components["schemas"]["PanelPosition"];
            minimapPosition: components["schemas"]["PanelPosition"];
            pathPosition: components["schemas"]["PanelPosition"];
            baseLightTheme: components["schemas"]["Themes"];
            baseDarkTheme: components["schemas"]["Themes"];
        };
        /** @description User settings. */
        Settings: {
            /** @default true */
            hideExtensions: boolean;
            /** @default master */
            defaultBranch: string;
            /** @default en */
            lang: string;
            style: components["schemas"]["Style"];
            keybinds: components["schemas"]["Keybinds"];
        };
        User: {
            name: string;
            email: string;
            has_github?: boolean;
            is_admin?: boolean;
            settings: components["schemas"]["Settings"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bc76a9d52929cab7a147ca7b5c527430: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login the user */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description User successfully logged in and token issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Error with login credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "250045954f07adf40103e33a04e5d715": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User successfully logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "0487fbb4c6d40e317fb4ec45582d09e5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to GitHub for authentication. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description GitHub client redirect not configured. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "34a24a8f777c83598c6c30936c6f9a04": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to the frontend URL after authentication. */
            301: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error during GitHub authentication. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apiRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create user model and login in user. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User successfully registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Error with registering. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "10eca818648caf716977d244ad606c5f": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All blocks, 1 deep, project has. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "1dd0ffd5fff7170b9eb63bc88abafb8e": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Name to crate the project */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoreBlockRequest"];
            };
        };
        responses: {
            /** @description Block created. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "620ba86a781f786819b86f7659a2ace8": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return block by id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            /** @description Block not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "6d6ed5337b57e93ccfc607d3ae3ead93": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block: number;
            };
            cookie?: never;
        };
        /** @description Data to update block. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateBlockRequest"];
            };
        };
        responses: {
            /** @description Block updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated/Invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "78f914110185aacb3dee70019e5a6e6b": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cc10f4e526e45e01f129e6568eb2aff6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block: number;
            };
            cookie?: never;
        };
        /** @description Data to update block. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateBlockRequest"];
            };
        };
        responses: {
            /** @description Block updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated/Invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    c857e2bdf63b37450c516ae264893aae: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block: Record<string, never>;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All blocks, from blocks deep. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "8d4a13ef3fc773ff4031e515460919ea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description test */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    a4dd4c17bf5fc24c224357f03dcc848a: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Name to crate the project */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoreProjectRequest"];
            };
        };
        responses: {
            /** @description Project created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            /** @description Invalid url */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"][];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "5dae9d6654a488de0a9e7fc0a8800669": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Project data */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoreClientProjectRequest"];
            };
        };
        responses: {
            /** @description Project created successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"][];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "1352e06e55f6ab10d3702509cd385918": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description test */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    a93b65e3037bfd5ea5cdc1b3dd11ba53: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        /** @description Date to update project. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "63c289a907902132dd95dd7ecb50143f": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ee35632abc0168537257bd8f5baa9f30: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        /** @description Date to update project. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    b890df2c0f1546a31de76aeaf6375924: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
                module: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description test */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LangObject"];
                };
            };
            /** @description Language/Module not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "971db9bc974c0e607288cfe7ecc10096": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    fd4f39f7820d3f3cbc259c5b30fed830: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User data to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    db0c8ea1c902ed078a87cf1fa6497994: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User password */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteUserRequest"];
            };
        };
        responses: {
            /** @description User deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    ea88adacb890b864b59bcce5aff2473d: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User data to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    f8741720bfaafb5c8126e8c1418a9917: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User style data to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateStyleRequest"];
            };
        };
        responses: {
            /** @description User style updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "54ba995c0c13dd114980733de45f7ffa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User style data to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateStyleRequest"];
            };
        };
        responses: {
            /** @description User style updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "57ddbc5bebe0cd30c268a0d8a4640660": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User password to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description User password updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "75f8f589d8162c3ebb0a27049232e804": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User password to update. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description User password updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "395814df2599dc7a564535035ede73fb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User repos from github. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    "5dcb8b09ef61f0dd409ac3fbf1c59d74": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repos url. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | null;
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
}
