/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "user": [],
    "user.settings": [],
    "user.repos": [],
    "projects.index": [],
    "projects.show": [
        {
            "name": "project",
            "required": true
        }
    ],
    "projects.store": [],
    "projects.update": [
        {
            "name": "project",
            "required": true
        }
    ],
    "projects.destroy": [
        {
            "name": "project",
            "required": true
        }
    ],
    "blocks.index": [
        {
            "name": "project",
            "required": true
        }
    ],
    "blocks.show": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.showBlocks": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.store": [],
    "blocks.update": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.destroy": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "auth.redirect": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
