name: Build and Store Docker Image

on:
  push:
    branches:
      - new-v

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t web-block:latest .
          docker save web-block:latest -o web-block.tar  # Save the image as a tarball

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: web-block.tar # Path to the tarball
