name: Node.js Build

on:
  push:
    branches:
      - new-v
  pull_request:
    branches:
      - new-v

jobs:
  node-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install
        working-directory: frontend # Specify the working directory for npm install

      - name: Run build
        run: npm run predeploy
        working-directory: frontend # Specify the working directory for npm run build

    #   - name: Run tests (optional)
    #     run: npm test # Uncomment this line if you want to run tests after building
